### ISSUE TITLE
nii2minc should not allow launching a task with one selection box left to default

### ISSUE THREAD

**Issue by prioux** [aces/cbrain-plugins-neuro#44]
There is a selection box in the nii2minc task view code that says:

```
 Write voxel data in type [selection box]
```

There are three values in it, but the task code allows launching a task with the blank value still selected, which crashes on the bourreau side with

```
 CbrainError: Unexpected voxel int sign
```

Adjust after_form().

**Comment by crocodoyle** [comment]
This appears to have been fixed already

**Comment by crocodoyle** [comment]
Can be closed

**Comment by prioux** [comment]
Not fixed. You have to select 'default' for the `voxel data type` box, then it allows the tasks to be launched with a blank entry for the `sign`, which crashes the task on the bourreau side.
